--- #YAML:1.0
name:               MailTools
version:            2.09
abstract:           Various e-mail related modules
author:
    - Mark Overmeer <perl@overmeer.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Format:  0
    Date::Parse:   0
    IO::Handle:    0
    Net::Domain:   1.05
    Net::SMTP:     1.03
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
